struct smx {
  void a() {}
  void b() {}
  void c() {}
  void d() {}
  void e() {}
  void f() {}
  void g() {}
  void h() {}
  void i() {}
  void j() {}
  void k() {}
  void l() {}
  void m() {}
  void n() {}
  void o() {}
  void p() {}
  void q() {}
  void r() {}
  void s() {}
  void t() {}
  void u() {}
  void v() {}
  void w() {}
  void x() {}
  void y() {}
  void z() {}
  void A() {}
  void B() {}
  void C() {}
  void D() {}
  void E() {}
  void F() {}
  void G() {}
  void H() {}
  void I() {}
  void J() {}
  void K() {}
  void L() {}
  void M() {}
  void N() {}
  void O() {}
  void P() {}
  void Q() {}
  void R() {}
  void S() {}
  void T() {}
  void U() {}
  void V() {}
  void W() {}
  void X() {}
  void Y() {}
  void Z() {}
};
